# Generated by Django 3.1.6 on 2021-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('reg_no', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('mob_no', models.IntegerField(max_length=10, unique=True)),
                ('dept', models.CharField(max_length=60)),
                ('tag', models.CharField(choices=[('Red', 'Red tag'), ('Grey', 'Grey tag'), ('Purple', 'Purple tag'), ('Orange', 'Orange tag')], max_length=6)),
                ('domain', models.CharField(choices=[('Tech', 'Tech domain'), ('Marketing', 'Marketing domain'), ('Design', 'Design domain'), ('Human Resources', 'Human resources domain')], max_length=20)),
            ],
        ),
    ]
