# Generated by Django 3.1.6 on 2021-07-27 05:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
